name: OpenShift CLI (oc) Runner
description: Action for running oc commands
branding:
  icon: package
  color: blue

inputs:
  ### Required
  commands:
    description: Command to run, will be prefaced by 'oc'; e.g. whoami
    required: true
  oc_namespace:
    description: OpenShift namespace (e.g. abc123-dev)
    required: true
  oc_server:
    description: OpenShift server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  oc_token:
    description: OpenShift access token
    required: true

  ### Usually a bad idea / not recommended
  oc_version:
    description: Override or non-default oc version; e.g. 4.13
    default: 'openshift-client-linux-4.14.41'

permissions: {}

runs:
  using: composite
  steps:
    # Override OpenShift version, if specified
    - name: Install CLI tools
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: ${{ inputs.oc_version }}

    - name: Command
      if: steps.diff.outputs.triggered == 'true'
      shell: bash
      run: |
        # Expand for deployment steps

        # Allow pipefail, since we could be catching nested/piped errors
        set +o pipefail

        # Login
        oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
        oc project ${{ inputs.oc_namespace }} #Safeguard!

        # Run command
        oc ${{ inputs.commands }}
