name: OpenShift CLI (oc) Runner
description: Action for running oc commands
branding:
  icon: package
  color: blue

inputs:
  ### Required
  commands:
    description: Command to run, will be prefaced by 'oc'; e.g. whoami
    required: true
  oc_namespace:
    description: OpenShift namespace (e.g. abc123-dev)
    required: true
  oc_server:
    description: OpenShift server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  oc_token:
    description: OpenShift access token
    required: true

  ### Usually a bad idea / not recommended
  oc_version:
    description: Override or non-default oc version; e.g. 4.13
    # default: 'openshift-client-linux-4.14.41'
    default: '4.14.41'

permissions: {}

runs:
  using: composite
  steps:
    # Override OpenShift version, if specified
    - name: Install CLI tools
      uses: redhat-actions/openshift-tools-installer@v1.13.1
      with:
        oc: ${{ inputs.oc_version }}
    
    - name: OpenShift Login
      shell: bash
      run: |
          # OC Login
          OC_TEMP_TOKEN=$(curl -k -X POST https://api.silver.devops.gov.bc.ca:6443/api/v1/namespaces/${{ inputs.oc_namespace }}/serviceaccounts/pipeline/token --header "Authorization: Bearer ${{ inputs.oc_token }}" -d '{"spec": {"expirationSeconds": 600}}' -H 'Content-Type: application/json; charset=utf-8' | jq -r '.status.token' )

          oc login --token=$OC_TEMP_TOKEN --server=https://api.silver.devops.gov.bc.ca:6443
          oc project ${{ inputs.oc_namespace }} # Safeguard!

    - name: Run Command
      shell: bash
      run: echo oc ${{ inputs.commands }}
