name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  whoami:
    name: Test Command
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - id: whoami
        uses: ./
        with:
          commands: oc whoami
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          oc_version: 4.16
          timeout: 1m
          triggers: ('.github/' 'action.yml')

      - if: steps.whoami.outputs.triggered != 'false'
        run: |
          # Verify outputs
          echo "Outputs: ${{ toJSON(steps.whoami.outputs) }}"
          if [ "${{ steps.whoami.outputs.triggered }}" != "true" ]; then
            echo "Error!  Verify outputs."
            exit 1
          fi


  repository:
    name: Test Non-Default Repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - id: repository
        uses: ./
        with:
          commands: |
            git remote -v
            if ! git config --get remote.origin.url | grep -q "bcgov/quickstart-openshift"; then
              echo "Error! Repository bcgov/quickstart-openshift is not checked out."
              exit 1
            else
              echo "Repository URL: $(git config --get remote.origin.url)"
              echo "Current Branch: $(git branch --show-current)"
            fi
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          repository: bcgov/quickstart-openshift
          ref: ''
          timeout: 1m
          triggers: ('.github/' 'action.yml')

      - run: |
          # Verify outputs
          echo "Outputs: ${{ toJSON(steps.repository.outputs) }}"
          if [ "${{ steps.repository.outputs.triggered }}" != "true" ]; then
            echo "Error!  Verify outputs."
            exit 1
          fi

  legacy:
    name: Test Legacy Binary
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          commands: oc version
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          oc_version: '4.1'
          timeout: 1m
          triggers: ('.github/' 'action.yml')

  cronjob:
    name: Test CronJob
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5      
      - id: cronjob
        uses: ./
        with:
          commands: oc process -f cronjob/openshift.deploy.yml -p ZONE=${{ github.event.number }} | oc apply -f -
          cronjob: ${{ github.event.repository.name }}-${{ github.event.number }}-cronjob
          cronjob_tail: -1
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          oc_version: latest
          timeout: 1m
          triggers: ('.github/' 'action.yml' 'cronjob/' 'scripts/run_cronjob.sh')

      - if: steps.cronjob.outputs.triggered != 'false'
        run: |
          # Verify outputs
          echo "Outputs: ${{ toJSON(steps.cronjob.outputs) }}"
          if [ "${{ steps.cronjob.outputs.job-name }}" == "" ]; then
            echo "Error!  Verify outputs."
            exit 1
          fi

  results:
    name: PR Results
    needs: [whoami, repository, legacy, cronjob]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
