name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  whoami:
    name: Who Am I?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: whoami
        uses: ./
        with:
          commands: oc whoami
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_server: ${{ secrets.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          triggers: ('.github/' 'action.yml' '.gitignore' 'LICENSE' 'README.md' 'renovate.json')

      - env:
          outputs: ${{ toJSON(steps.whoami.outputs) }}
        if: steps.whoami.outputs.triggered == 'true'
        run: |
          echo "Outputs: ${{ env.outputs }}"

      - if: steps.whoami.outputs.triggered != 'true'
        run: |
          echo "Error!  Verify outputs."
          echo "Outputs: ${{ steps.whoami }}"
          exit 1

  legacy:
    name: Legacy Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          commands: oc version
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_server: ${{ secrets.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          oc_version: '4.1'
          triggers: ('./github/' 'action.yml')

  results:
    name: PR Results
    needs: [whoami, legacy]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
