name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: ./
        with:
          commands: whoami
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_server: ${{ secrets.oc_server }}
          oc_token: ${{ secrets.oc_token }}
